title: Blessing Okeke # your name (or website title) here
logo: "/blossom.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst | SQL | Python | Tableau | Excel
  <br><br>
  Mathematician 
  <br><br>
  <a href="https://www.linkedin.com/in/blessing-okeke-338559212">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://twitter.com/Blossombaby14">View My Twitter Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
